// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtupuqo2oUW5GtREil7ufnxmkomK3VAW0',
    appId: '1:979330270552:web:c6afa6641bbdac1f56512d',
    messagingSenderId: '979330270552',
    projectId: 'live-mus',
    authDomain: 'live-mus.firebaseapp.com',
    databaseURL: 'https://live-mus-default-rtdb.firebaseio.com',
    storageBucket: 'live-mus.firebasestorage.app',
    measurementId: 'G-30YZN7FDF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVDccLi4MPtugSptWv_la-MX0BQDyjTs',
    appId: '1:979330270552:android:0bced7a78696208c56512d',
    messagingSenderId: '979330270552',
    projectId: 'live-mus',
    databaseURL: 'https://live-mus-default-rtdb.firebaseio.com',
    storageBucket: 'live-mus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBca3f6MkFwwin9ZDWu2Wh5uNYHdp6zDzo',
    appId: '1:979330270552:ios:06830eb5ad3c3ee656512d',
    messagingSenderId: '979330270552',
    projectId: 'live-mus',
    databaseURL: 'https://live-mus-default-rtdb.firebaseio.com',
    storageBucket: 'live-mus.firebasestorage.app',
    androidClientId:
        '979330270552-h5eeuioomgj7kd5p97r8mnm9mec3ievc.apps.googleusercontent.com',
    iosClientId:
        '979330270552-c9eevtm2tecmfi49m32fl6rau2t658sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveMusic4',
  );
}
